import 'package:flutter_test/flutter_test.dart';
import 'package:our_spends/services/ai_service.dart';
import 'package:our_spends/services/database_service.dart';
import 'package:our_spends/models/expense.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  group('AI and Database Integration Tests', () {
    late AIService aiService;
    late DatabaseService databaseService;
    
    setUp(() async {
      // Initialize SharedPreferences mock
      SharedPreferences.setMockInitialValues({
        'ai_provider': 'gemini', // Set default provider for testing
      });
      
      // Create service instances
      aiService = AIService();
      databaseService = DatabaseService();
      
      // Initialize the services
      await aiService.initialize();
      await databaseService.init();
    });

    test('Extract expense and save to database', () async {
      // Skip if API key is not configured
      if (const String.fromEnvironment('GEMINI_API_KEY').isEmpty) {
        markTestSkipped('Skipping test because GEMINI_API_KEY is not set');
        return;
      }
      
      const userId = 'test-user-id';
      const message = 'I spent \$50 on groceries yesterday';
      
      // Process the message with AI service
      final conversationHistory = <Map<String, String>>[];
      final userExpenses = <Expense>[];
      // Process message but don't use the result since we're using extractExpenseInfo directly
      await aiService.processMessage(
        message,
        userExpenses,
        conversationHistory: conversationHistory,
        languageCode: 'en',
      );
      
      // Extract expense information
      final expenseInfo = await aiService.extractExpenseInfo(message);
      
      // Verify AI extracted the expense information
      expect(expenseInfo, isNotNull);
      expect(expenseInfo!['amount'], 50.0);
      expect(expenseInfo['description'] ?? expenseInfo['item'], contains('groceries'));
      
      // Create an expense object from the extracted information
      final yesterday = DateTime.now().subtract(const Duration(days: 1));
      final dateTime = DateTime(
        yesterday.year,
        yesterday.month,
        yesterday.day,
      );
      
      final expense = Expense(
        id: '', // Will be generated by database service
        userId: userId,
        date: dateTime,
        amount: expenseInfo['amount'] is double 
            ? expenseInfo['amount'] 
            : double.parse(expenseInfo['amount'].toString()),
        currency: expenseInfo['currency'] ?? 'USD',
        category: expenseInfo['category'] == 'food' ? 'Food & Dining' : 'Other',
        item: expenseInfo['description'] ?? expenseInfo['item'] ?? 'Expense',
        description: expenseInfo['description'],
        location: expenseInfo['location'] ?? 'Unknown',
      );
      
      // Save the expense to the database
      final expenseId = await databaseService.insertExpense(expense);
      
      // Verify the expense was saved
      expect(expenseId, isNotNull);
      expect(expenseId, isNotEmpty);
      
      // Retrieve the expense from the database
      final expenses = await databaseService.getExpenses();
      
      // Verify the expense was retrieved
      expect(expenses, isNotEmpty);
      
      // Find the saved expense
      final savedExpense = expenses.firstWhere((e) => e.id == expenseId);
      
      // Verify the expense details
      expect(savedExpense.amount, 50.0);
      expect(savedExpense.category, 'Food & Dining');
      expect(savedExpense.item, contains('groceries'));
      expect(savedExpense.date.year, dateTime.year);
      expect(savedExpense.date.month, dateTime.month);
      expect(savedExpense.date.day, dateTime.day);
    });

    test('Generate spending insights from database expenses', () async {
      // Skip if API key is not configured
      if (const String.fromEnvironment('GEMINI_API_KEY').isEmpty) {
        markTestSkipped('Skipping test because GEMINI_API_KEY is not set');
        return;
      }
      
      const userId = 'test-user-id';
      
      // Create test expenses
      final today = DateTime.now();
      final yesterday = today.subtract(const Duration(days: 1));
      
      final expenses = [
        Expense(
          id: '1',
          userId: userId,
          date: today,
          amount: 50.0,
          currency: 'USD',
          category: 'Food & Dining',
          item: 'Lunch',
        ),
        Expense(
          id: '2',
          userId: userId,
          date: yesterday,
          amount: 30.0,
          currency: 'USD',
          category: 'Transportation',
          item: 'Taxi',
        ),
      ];
      
      // Save expenses to the database
      for (final expense in expenses) {
        await databaseService.insertExpense(expense);
      }
      
      // Retrieve expenses from the database
      final dbExpenses = await databaseService.getExpenses();
      
      // Generate spending insights
      final insights = await aiService.generateSpendingInsights(dbExpenses);
      
      // Verify insights are not empty
      expect(insights, isNotNull);
      expect(insights.isNotEmpty, isTrue);
      
      // Verify insights contain relevant information
      expect(insights, anyOf(contains('50'), contains('USD')));
      expect(insights, anyOf(contains('30'), contains('USD')));
      expect(insights, anyOf(contains('Food'), contains('Dining'), contains('Lunch')));
      expect(insights, anyOf(contains('Transportation'), contains('Taxi')));
    });
  });
}