import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:our_spends/models/expense.dart';
import 'package:our_spends/services/database_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  group('Database Service Persistence Tests', () {
    late DatabaseService databaseService;
    
    setUp(() {
      databaseService = DatabaseService();
    });
    
    test('should persist expenses between app restarts', () async {
      // Setup SharedPreferences mock with empty initial values
      SharedPreferences.setMockInitialValues({});
      
      // Initialize database
      await databaseService.init();
      
      // Create a single test expense
      final testExpense = Expense(
        id: '',  // ID will be generated by the service
        userId: 'test-user',
        date: DateTime(2023, 5, 15),
        amount: 50.0,
        currency: 'USD',
        category: 'Food & Dining',
        item: 'Lunch',
      );
      
      // Insert expense
      final expenseId = await databaseService.insertExpense(testExpense);
      
      // Verify expense was saved in memory
      var expenses = await databaseService.getExpenses();
      expect(expenses.length, 1);
      expect(expenses[0].amount, 50.0);
      expect(expenses[0].item, 'Lunch');
      
      // Verify data was saved to SharedPreferences
      final prefs = await SharedPreferences.getInstance();
      final expensesJson = prefs.getString('expenses_data');
      expect(expensesJson, isNotNull);
      
      // Verify the saved JSON contains the expense
      final List<dynamic> savedExpenses = json.decode(expensesJson!);
      expect(savedExpenses.length, 1);
      
      // Simulate app restart by creating a new database service instance
      final newDatabaseService = DatabaseService();
      await newDatabaseService.init();
      
      // Verify expense is still available after "restart"
      expenses = await newDatabaseService.getExpenses();
      expect(expenses.length, 1);
      
      // Verify expense details were preserved
      expect(expenses[0].id, expenseId);
      expect(expenses[0].amount, 50.0);
      expect(expenses[0].category, 'Food & Dining');
      expect(expenses[0].item, 'Lunch');
    });
    
    test('should persist expense updates', () async {
      // Setup SharedPreferences mock with empty initial values
      SharedPreferences.setMockInitialValues({});
      
      // Initialize database
      await databaseService.init();
      
      // Create and insert test expense
      final testExpense = Expense(
        id: '',  // ID will be generated by the service
        userId: 'test-user',
        date: DateTime(2023, 5, 15),
        amount: 50.0,
        currency: 'USD',
        category: 'Food & Dining',
        item: 'Original expense',
      );
      
      final expenseId = await databaseService.insertExpense(testExpense);
      
      // Retrieve the saved expense
      var savedExpense = await databaseService.getExpenseById(expenseId);
      expect(savedExpense, isNotNull);
      
      // Update the expense
      final updatedExpense = savedExpense!.copyWith(
        amount: 75.0,
        item: 'Updated expense',
      );
      
      await databaseService.updateExpense(updatedExpense);
      
      // Verify update was saved to SharedPreferences
      final prefs = await SharedPreferences.getInstance();
      final expensesJson = prefs.getString('expenses_data');
      expect(expensesJson, isNotNull);
      
      // Verify the saved JSON contains the updated expense
      final List<dynamic> savedExpenses = json.decode(expensesJson!);
      expect(savedExpenses.length, 1);
      final Map<String, dynamic> savedExpenseJson = savedExpenses[0];
      expect(savedExpenseJson['amount'], 75.0);
      expect(savedExpenseJson['item'], 'Updated expense');
      
      // Simulate app restart
      final newDatabaseService = DatabaseService();
      await newDatabaseService.init();
      
      // Verify update was persisted
      savedExpense = await newDatabaseService.getExpenseById(expenseId);
      expect(savedExpense, isNotNull);
      expect(savedExpense?.amount, 75.0);
      expect(savedExpense?.item, 'Updated expense');
    });
    
    test('should persist expense deletion', () async {
      // Setup SharedPreferences mock with empty initial values
      SharedPreferences.setMockInitialValues({});
      
      // Initialize database
      await databaseService.init();
      
      // Create and insert a single test expense
      final testExpense = Expense(
        id: '',
        userId: 'test-user',
        date: DateTime(2023, 5, 15),
        amount: 50.0,
        currency: 'USD',
        category: 'Food & Dining',
        item: 'Test Expense',
      );
      
      // Insert expense
      final expenseId = await databaseService.insertExpense(testExpense);
      
      // Verify expense was saved
      var expenses = await databaseService.getExpenses();
      expect(expenses.length, 1, reason: 'Should have one expense after insertion');
      
      // Get the SharedPreferences instance to verify data was actually saved
      var prefs = await SharedPreferences.getInstance();
      var expensesJson = prefs.getString('expenses_data');
      expect(expensesJson, isNotNull, reason: 'Expenses data should be saved in SharedPreferences');
      
      // Verify the saved JSON contains one expense
      var savedExpenses = json.decode(expensesJson!);
      expect(savedExpenses.length, 1, reason: 'Should have one expense in SharedPreferences');
      
      // Delete the expense
      await databaseService.deleteExpense(expenseId);
      
      // Verify expense was deleted from memory
      expenses = await databaseService.getExpenses();
      expect(expenses.length, 0, reason: 'Should have no expenses after deletion');
      
      // Verify expense was deleted from SharedPreferences
      prefs = await SharedPreferences.getInstance();
      expensesJson = prefs.getString('expenses_data');
      expect(expensesJson, isNotNull, reason: 'Expenses data should still exist in SharedPreferences');
      
      savedExpenses = json.decode(expensesJson!);
      expect(savedExpenses.length, 0, reason: 'Should have no expenses in SharedPreferences after deletion');
      
      // Create a new database service to simulate app restart
      final newDatabaseService = DatabaseService();
      await newDatabaseService.init();
      
      // Verify expense is still deleted after "restart"
      final persistedExpenses = await newDatabaseService.getExpenses();
      expect(persistedExpenses.length, 0, reason: 'Should have no expenses after app restart');
    });
  });
}