// Mocks generated by Mockito 5.4.6 from annotations
// in our_spends/test/screens/ai_chat_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:our_spends/models/category.dart' as _i9;
import 'package:our_spends/models/expense.dart' as _i4;
import 'package:our_spends/models/tag.dart' as _i10;
import 'package:our_spends/providers/expense_provider.dart' as _i3;
import 'package:our_spends/providers/language_provider.dart' as _i6;
import 'package:our_spends/services/ai_service.dart' as _i11;
import 'package:our_spends/services/database_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocale_0 extends _i1.SmartFake implements _i2.Locale {
  _FakeLocale_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseProvider extends _i1.Mock implements _i3.ExpenseProvider {
  MockExpenseProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Expense> get expenses =>
      (super.noSuchMethod(
            Invocation.getter(#expenses),
            returnValue: <_i4.Expense>[],
          )
          as List<_i4.Expense>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Stream<List<_i4.Expense>> get expensesStream =>
      (super.noSuchMethod(
            Invocation.getter(#expensesStream),
            returnValue: _i5.Stream<List<_i4.Expense>>.empty(),
          )
          as _i5.Stream<List<_i4.Expense>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Map<String, dynamic>> sendMessage(
    String? message,
    String? userId, {
    List<Map<String, String>>? conversationHistory,
    String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [message, userId],
              {
                #conversationHistory: conversationHistory,
                #languageCode: languageCode,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> generateInsights(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateInsights, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadExpensesForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#loadExpensesForTesting, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> addExpense(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#addExpense, [expense]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> deleteExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LanguageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageProvider extends _i1.Mock implements _i6.LanguageProvider {
  MockLanguageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Locale get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeLocale_0(this, Invocation.getter(#currentLocale)),
          )
          as _i2.Locale);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> changeLanguage(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [languageCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getCurrentLanguageName() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLanguageName, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getCurrentLanguageName, []),
            ),
          )
          as String);

  @override
  String getLanguageName(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getLanguageName, [code]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getLanguageName, [code]),
            ),
          )
          as String);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i8.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.Expense>> getExpenses({
    String? categoryId,
    DateTime? startDate,
    DateTime? endDate,
    double? minAmount,
    double? maxAmount,
    String? searchQuery,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenses, [], {
              #categoryId: categoryId,
              #startDate: startDate,
              #endDate: endDate,
              #minAmount: minAmount,
              #maxAmount: maxAmount,
              #searchQuery: searchQuery,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<_i4.Expense>>.value(<_i4.Expense>[]),
          )
          as _i5.Future<List<_i4.Expense>>);

  @override
  _i5.Future<_i4.Expense?> getExpenseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenseById, [id]),
            returnValue: _i5.Future<_i4.Expense?>.value(),
          )
          as _i5.Future<_i4.Expense?>);

  @override
  _i5.Future<String> insertExpense(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#insertExpense, [expense]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertExpense, [expense]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateExpense(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteExpense(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getDatabaseStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabaseStats, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getExpensesByCategory({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategory, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getSpendingTrends({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSpendingTrends, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<double> getMonthlySpending(int? year, int? month) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySpending, [year, month]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<List<_i4.Expense>> searchExpenses(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExpenses, [query]),
            returnValue: _i5.Future<List<_i4.Expense>>.value(<_i4.Expense>[]),
          )
          as _i5.Future<List<_i4.Expense>>);

  @override
  _i5.Future<List<_i9.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<_i9.Category>>.value(<_i9.Category>[]),
          )
          as _i5.Future<List<_i9.Category>>);

  @override
  _i5.Future<_i9.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i5.Future<_i9.Category?>.value(),
          )
          as _i5.Future<_i9.Category?>);

  @override
  _i5.Future<List<_i10.Tag>> getTags() =>
      (super.noSuchMethod(
            Invocation.method(#getTags, []),
            returnValue: _i5.Future<List<_i10.Tag>>.value(<_i10.Tag>[]),
          )
          as _i5.Future<List<_i10.Tag>>);

  @override
  _i5.Future<_i10.Tag?> getTagById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTagById, [id]),
            returnValue: _i5.Future<_i10.Tag?>.value(),
          )
          as _i5.Future<_i10.Tag?>);

  @override
  _i5.Future<String> exportToCSV({DateTime? startDate, DateTime? endDate}) =>
      (super.noSuchMethod(
            Invocation.method(#exportToCSV, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#exportToCSV, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i11.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> processMessage(
    String? message,
    List<_i4.Expense>? userExpenses, {
    List<Map<String, String>>? conversationHistory,
    String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processMessage,
              [message, userExpenses],
              {
                #conversationHistory: conversationHistory,
                #languageCode: languageCode,
              },
            ),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #processMessage,
                  [message, userExpenses],
                  {
                    #conversationHistory: conversationHistory,
                    #languageCode: languageCode,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>?> extractExpenseInfo(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#extractExpenseInfo, [message]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<String> generateSpendingInsights(List<_i4.Expense>? expenses) =>
      (super.noSuchMethod(
            Invocation.method(#generateSpendingInsights, [expenses]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#generateSpendingInsights, [expenses]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> testGemini() =>
      (super.noSuchMethod(
            Invocation.method(#testGemini, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  String getProviderName() =>
      (super.noSuchMethod(
            Invocation.method(#getProviderName, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getProviderName, []),
            ),
          )
          as String);

  @override
  String getProviderModel() =>
      (super.noSuchMethod(
            Invocation.method(#getProviderModel, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getProviderModel, []),
            ),
          )
          as String);

  @override
  _i5.Future<bool> isGeminiAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isGeminiAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getGeminiStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGeminiStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
